const qa=document.createElement('details');
qa.style.cssText='position:fixed;bottom:10px;left:10px;z-index:10000;background:white;border:2px solid #0752a2;border-radius:10px;color:#073464;padding:10px;font:13px Arial;max-width:90vw;max-height:42vh;overflow:auto';
qa.innerHTML='<summary id="qa-status">Testes de anexos preparados</summary><button id="qa-run">Testar anexos</button> <button id="qa-demo">Abrir editor de teste</button><p>Leitor PDF nativo: '+navigator.pdfViewerEnabled+'</p><ol id="qa-results"></ol>';
document.body.append(qa);
let n=0;
const ok=(cond,text)=>{const li=document.createElement('li');li.textContent=(cond?'OK: ':'FALHA: ')+text;document.getElementById('qa-results').append(li);if(!cond)throw Error(text);document.getElementById('qa-status').textContent=++n+' testes aprovados';};
const abrir=async(id='os440',aba)=>{await abrirPagina(id,null,aba||Dashboard.contratos[id].abas[0].id);Render.atualizar();};
const pdf=async(nome='documento.pdf')=>new File([await (await fetch('/qa/sample.pdf')).arrayBuffer()],nome,{type:'application/pdf'});
const omAtual=()=>EditorRelatorio.rascunho.atividades[0].oms[0];
const campo=(nome,g=0,o=0)=>document.querySelector(`[data-campo="${nome}"][data-grupo="${g}"][data-om="${o}"]`);
const preencher=(nome,valor)=>{campo(nome).value=valor;campo(nome).dispatchEvent(new Event('input',{bubbles:true}));};
document.getElementById('qa-demo').onclick=async()=>{
 if(EditorRelatorio.ativo)EditorRelatorio.cancelar();sessaoAnexosTeste('editor');await abrir();EditorRelatorio.iniciar();
 AnexosOM.adicionar(omAtual(),await pdf('Relatório complementar com nome bastante longo para conferir a leitura no celular e no computador.pdf'),'relatorio');
 EditorRelatorio.renderizarSomenteAtividades();qa.open=false;
};
document.getElementById('qa-run').onclick=async()=>{
 n=0;document.getElementById('qa-results').replaceChildren();const originals=structuredClone(Dashboard.contratos);
 try{
  if(EditorRelatorio.ativo)EditorRelatorio.cancelar();AnexosOM.destruir();await abrir();
  for(const role of ['visualizador','editor','planejamento','admin']){
   sessaoAnexosTeste(role);const can=role!=='visualizador';
   ok(document.querySelector('#os440-content [data-abrir-editor]').hidden===!can,'Permissão de '+role);
   ok(EditorRelatorio.iniciar()===can,'Início autorizado: '+role);if(can)EditorRelatorio.cancelar();
  }
  sessaoAnexosTeste('editor');
  for(const [id,c]of Object.entries(Dashboard.contratos))for(const a of c.abas){
   await abrir(id,a.id);EditorRelatorio.iniciar();ok(EditorRelatorio.validar().length===0,'Compatibilidade '+id+'/'+a.id);
   ok(JSON.stringify(EditorRelatorio.gerarPayload()).length>0,'Payload serializável '+id+'/'+a.id);EditorRelatorio.cancelar();
  }
  await abrir();const original=JSON.stringify(Dashboard.abaAtual);EditorRelatorio.iniciar();
  const arquivo=await pdf(), om=omAtual();
  const semDocumento=EditorRelatorio.rascunho.atividades.find(g=>(g.oms||[]).some(o=>!o.arquivoPdf&&!o.arquivoLaudo)).oms.find(o=>!o.arquivoPdf&&!o.arquivoLaudo);
  const primeiroSemDocumento=AnexosOM.adicionar(semDocumento,arquivo,'om');
  ok(semDocumento.anexos[0].id===primeiroSemDocumento.id && !om.anexos,'PDF adicionado à OM sem documentos sem afetar outra OM');
  AnexosOM.remover(semDocumento,primeiroSemDocumento.id);
  const novo=AnexosOM.adicionar(om,arquivo,'laudo');EditorRelatorio.renderizarSomenteAtividades();
  ok(om.anexos.length===1 && EditorRelatorio.rascunho.atividades[1].oms[0].anexos===undefined,'Anexo somente na OM selecionada');
  ok(AnexosOM.arquivosPendentes.get(novo.id)===arquivo,'File no registro separado');
  ok(JSON.stringify(Dashboard.abaAtual)===original,'Estado aplicado intacto durante edição');
  const payload=EditorRelatorio.gerarPayload();
  ok(JSON.parse(JSON.stringify(payload)).dados.atividades[0].oms[0].anexos[0].nome===arquivo.name,'Metadados serializáveis no payload');
  ok(!Object.values(novo).some(v=>v instanceof Blob)&&!JSON.stringify(payload).includes('blob:'),'Sem File, Blob ou objectURL no payload');
  ok(novo.storagePath===null && novo.categoria==='laudo'&&novo.mimeType==='application/pdf','Categoria independente do MIME e Storage nulo');
  await AnexosOM.visualizar(novo.id);const url=AnexosOM.urlsTemporarias.get(novo.id);
  ok(navigator.pdfViewerEnabled===false ? document.querySelector('.anexo-preview').textContent.includes('não oferece visualização de PDF') : document.querySelector('.anexo-preview iframe').src===url,'PDF usa visualizador nativo ou fallback explícito');
  ok((await fetch(url)).status===200,'Prévia aponta para bytes acessíveis');
  AnexosOM.fecharDialogo();ok(AnexosOM.urlsTemporarias.size===0,'Fechar prévia revoga URL');
  let revogada=false;try{await fetch(url);}catch{revogada=true;}ok(revogada,'URL revogada não entrega bytes');
  const mesmoNome=AnexosOM.adicionar(om,arquivo,'om');ok(mesmoNome.id!==novo.id,'Mesmo nome de arquivo recebe IDs distintos');
  await AnexosOM.visualizar(novo.id);AnexosOM.remover(om,novo.id);AnexosOM.fecharDialogo();
  ok(!om.anexos.some(a=>a.id===novo.id)&&!AnexosOM.arquivosPendentes.has(novo.id)&&!AnexosOM.urlsTemporarias.has(novo.id),'Remover limpa metadado, File e preview');
  EditorRelatorio.cancelar();ok(AnexosOM.arquivosPendentes.size===0&&AnexosOM.urlsTemporarias.size===0&&JSON.stringify(Dashboard.abaAtual)===original,'Cancelar descarta arquivos e alterações da sessão');
  const legacy={numero:'QA',arquivoPdf:'/qa/sample.pdf',arquivoLaudo:'/qa/sample.pdf'};
  const legadoHTML=AnexosOM.render(legacy,{editavel:true});
  ok((legadoHTML.match(/Documento existente/g)||[]).length===2,'PDF e laudo legados reconhecidos sem migração');
  ok(!legacy.anexos&&!legadoHTML.includes('data-anexo-remover'),'Legados não migrados nem removíveis');
  ok((await fetch(AnexosOM.documentosLegados(legacy)[1].url)).ok,'Laudo legado disponível pode ser aberto');
  ok(AnexosOM.documentosLegados({pdf:'/qa/sample.pdf',laudo:'/qa/sample.pdf'}).length===2,'Aliases antigos pdf e laudo preservados');
  ok(AnexosOM.render({numero:'sem'}).length===0&&AnexosOM.render({anexos:[]}).length===0,'OM sem documentos e anexos vazio tolerados');
  ok(AnexosOM.render({anexos:[{id:'persistido',nome:'Arquivo remoto',categoria:'om',storagePath:'futuro/p.pdf'}]},{editavel:true}).includes('Documento persistido'),'Metadado persistido tolerado sem inventar URL remota');
  ok(AnexosOM.urlDocumento('javascript:alert(1)')===null,'Links ativos indevidos bloqueados');
  EditorRelatorio.iniciar();const om1=omAtual();const one=AnexosOM.adicionar(om1,arquivo,'om');
  const om2=EditorRelatorio.rascunho.atividades[1].oms[0];const two=AnexosOM.adicionar(om2,new File(['segundo'],'outro.txt',{type:'text/plain'}),'outro');
  preencher('descricao','Descrição QA anexo');preencher('status','Concluída');EditorRelatorio.definirLocalizacao(0,0,-2.55,-44.35);
  ok(om1.anexos[0].id===one.id&&om2.anexos[0].id===two.id,'Editar descrição, status e coordenadas mantém associações distintas');
  const grupo=Dashboard.abaAtual.atividades[0],ctx={contrato:Dashboard.contratoAtual,aba:Dashboard.abaAtual};
  const chaveAntes=MapaPainel.chaveFoto(grupo.oms[0],grupo,ctx);const db=await MapaPainel.abrirBancoFotos();
  const bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZioAAAAASUVORK5CYII='),c=>c.charCodeAt(0));
  const fotoId=await MapaPainel.salvarFotoBanco(db,{chave:chaveAntes,blob:new Blob([bytes],{type:'image/png'}),nome:'teste-foto.png',criadaEm:Date.now()});
  EditorRelatorio.iniciarSelecaoLocalizacao(0,0);const mapa=Mapa.map;Mapa.atualizarPontoSelecao({lat:-2.551,lng:-44.351});Mapa.confirmarSelecaoLocalizacao();
  ok(om1.anexos[0].id===one.id&&Mapa.map===mapa,'Mapa reutilizado e anexos intactos');
  const paraSalvar=EditorRelatorio.gerarPayload();ok(AnexosOM.obterArquivosParaPayload(paraSalvar).size===2,'Binários disponíveis separadamente para futura persistência');
  ok(EditorRelatorio.aplicar(),'Aplicar continua funcionando');
  ok(AnexosOM.arquivosPendentes.size===0&&AnexosOM.arquivosAplicados.size===2,'Aplicar transfere binários ao registro da página');
  ok(document.querySelectorAll('#os440-content [data-anexo-card]').length===2,'Anexos aparecem na visualização normal');
  await AnexosOM.visualizar(one.id);ok(!!document.querySelector('.anexo-preview a[download]'),'Acesso ao arquivo continua após aplicar');AnexosOM.fecharDialogo();
  const grupoAtual=Dashboard.abaAtual.atividades[0];const chaveDepois=MapaPainel.chaveFoto(grupoAtual.oms[0],grupoAtual,ctx);
  ok(chaveAntes===chaveDepois&&(await MapaPainel.buscarFotosBanco(db,chaveDepois)).some(f=>f.id===fotoId),'Fotos preservadas após anexar e editar');
  const pin=Mapa.montarMarcadores(Dashboard.contratoAtual).find(p=>p.frente===grupoAtual.oms[0].frente);
  Mapa.abrirPainel(pin);await MapaPainel.hidratarFotos(document.getElementById('mapa-painel-conteudo'));
  ok(!!document.querySelector('#mapa-painel-conteudo .mapa-painel-foto-thumb img'),'Foto renderizada no mapa');
  ok(!!document.querySelector(`#mapa-painel-conteudo [data-anexo-card="${one.id}"]`),'Novo documento exibido na OM do painel do mapa');
  EditorRelatorio.iniciar();const appliedOM=omAtual();AnexosOM.remover(appliedOM,one.id);const temp=AnexosOM.adicionar(appliedOM,arquivo,'outro');EditorRelatorio.cancelar();
  ok(AnexosOM.arquivo(one.id)&&!AnexosOM.arquivo(temp.id)&&Dashboard.abaAtual.atividades[0].oms[0].anexos.some(a=>a.id===one.id),'Cancelar reedição mantém aplicado e descarta somente novos');
  EditorRelatorio.iniciar();AnexosOM.remover(omAtual(),one.id);EditorRelatorio.aplicar();
  ok(!AnexosOM.arquivo(one.id)&&AnexosOM.arquivo(two.id),'Aplicar remoção libera somente o binário sem referências');
  EditorRelatorio.iniciar();const g=EditorRelatorio.rascunho.atividades.length;EditorRelatorio.adicionarGrupo();EditorRelatorio.adicionarOM(g);
  const omNova=EditorRelatorio.rascunho.atividades[g].oms[0];const del=AnexosOM.adicionar(omNova,arquivo,'om');EditorRelatorio.removerOM(g,0);
  ok(!AnexosOM.arquivo(del.id),'Remover OM nova limpa seus anexos temporários');
  EditorRelatorio.adicionarOM(g);AnexosOM.adicionar(EditorRelatorio.rascunho.atividades[g].oms[0],arquivo,'om');
  const grupoRemover=EditorRelatorio.removerGrupo(g);document.querySelector('[data-aceitar]').click();await grupoRemover;
  ok(AnexosOM.arquivosPendentes.size===0,'Remover grupo limpa anexos temporários');
  let count=AnexosOM.arquivosPendentes.size;try{AnexosOM.adicionar(omAtual(),new File([], 'vazio.pdf'),'om');}catch{}
  ok(AnexosOM.arquivosPendentes.size===count,'Arquivo vazio rejeitado');
  ok(!!AnexosOM.validarArquivo(new File([new Uint8Array(AnexosOM.MAX_ANEXO_BYTES+1)],'grande.pdf')),'Limite configurável bloqueia arquivo excessivo');
  ok(!AnexosOM.validarArquivo(new File(['zip'],'desenho.dwg')),'Formatos não PDF permitidos');
  const inseguro=AnexosOM.adicionar(omAtual(),new File(['<script>alert(1)</script>'],'documento.html',{type:'text/html'}),'outro');
  await AnexosOM.visualizar(inseguro.id);ok(!document.querySelector('.anexo-preview iframe')&&document.querySelector('.anexo-preview a[download]'),'Formato ativo oferecido somente para download');AnexosOM.fecharDialogo();
  for(const value of [new File(['x'],'x.txt'),new Blob(['x']),'blob:teste']){let rejeitado=false;try{AnexosOM.garantirPayloadSerializavel({dados:value});}catch{rejeitado=true;}ok(rejeitado,'Proteção de payload: '+(typeof value==='string'?'URL':value.constructor.name));}
  const htmlTeste=AnexosOM.adicionar(omAtual(),new File(['x'],'<img src=x onerror=alert(1)>.txt',{type:'text/plain'}),'outro');
  EditorRelatorio.renderizarSomenteAtividades();ok(!document.querySelector('.om-anexos img')&&document.querySelector(`[data-anexo-card="${htmlTeste.id}"] strong`).textContent.startsWith('<img'),'Nome de arquivo exibido como texto seguro');
  await AnexosOM.visualizar(htmlTeste.id);sessaoAnexosTeste('visualizador');
  ok(!EditorRelatorio.ativo&&!AnexosOM.dialogo&&!AnexosOM.arquivosPendentes.size&&!AnexosOM.urlsTemporarias.size,'Perda de permissão limpa arquivos e prévias da edição');
  ok(!!AnexosOM.arquivo(two.id),'Arquivo aplicado continua controlado pela página');
  sessaoAnexosTeste('editor');EditorRelatorio.iniciar();EditorRelatorio.adicionarGrupo();
  const grupoNovo=EditorRelatorio.rascunho.atividades.length-1;
  EditorRelatorio.adicionarOM(grupoNovo);EditorRelatorio.adicionarOM(grupoNovo);
  const novas=EditorRelatorio.rascunho.atividades[grupoNovo].oms;
  Object.assign(novas[0],{numero:'QA-1',frente:'NOVA-1',descricao:'Nova OM 1'});Object.assign(novas[1],{numero:'QA-2',frente:'NOVA-2',descricao:'Nova OM 2'});
  const a1=AnexosOM.adicionar(novas[0],arquivo,'om');const a2=AnexosOM.adicionar(novas[1],new File(['conteudo 2'],'distinto.txt',{type:'text/plain'}),'outro');
  ok(novas[0].anexos[0].id!==novas[1].anexos[0].id&&AnexosOM.arquivo(a1.id).name==='documento.pdf'&&AnexosOM.arquivo(a2.id).name==='distinto.txt','Duas OMs novas mantêm binários distintos');
  await AnexosOM.visualizar(a2.id);ok(document.querySelector('.anexo-preview pre').textContent==='conteudo 2','Prévia de texto renderiza conteúdo local');AnexosOM.fecharDialogo();
  const textoImagem=AnexosOM.adicionar(novas[0],new File([bytes],'evidencia.png',{type:'image/png'}),'evidencia');
  await AnexosOM.visualizar(textoImagem.id);ok(!!document.querySelector('.anexo-preview img'),'Documento imagem tem prévia sem migrar fotos');AnexosOM.fecharDialogo();
  const falsoPdf=AnexosOM.adicionar(novas[0],new File(['<html>não PDF</html>'],'falso.pdf',{type:'application/pdf'}),'outro');
  await AnexosOM.visualizar(falsoPdf.id);ok(!document.querySelector('.anexo-preview iframe'),'Arquivo sem cabeçalho PDF não executa como prévia');AnexosOM.fecharDialogo();
  EditorRelatorio.cancelar();
  AnexosOM.destruir();Object.assign(Dashboard.contratos,originals);sessaoAnexosTeste('editor');await abrir();
  document.getElementById('qa-status').textContent='CONCLUÍDO — '+n+' testes aprovados';
 }catch(error){console.error('QA anexos:',error);document.getElementById('qa-status').textContent='FALHOU — '+error.message;}
};
